/*
 * Emulation of the HLS-implemented FPGA-based DAQ engine for QEMU
 *
 * Copyright Wojciech M. Zabolotny ( wzab@ise.pw.edu.pl ) 2021, 2022
 *
 * Development of the model is partially supported by the
 * European Union’s Horizon 2020 research and innovation programme
 * under grant agreement No 871072.
 * 
 * The driver and application to the model is available at:
 * https://gitlab.com/WZab/wzdaq_drv   
 *
 * === NEW DESCRIPTION (incomplete yet) ===
 * The code uses the header files generated by HLS - xdma1_hw.h
 *
 * The registers:
 * DESCS - Stores the DMA address of the huge page keeping the descriptors.
 * NOF_BUFS - Stores the number of huge page buffers (may be smaller
 *            than the maximum number defined in the HW by BUFS_?_HIGH-BUFS 
 * CUR_BUF - Stores the number of the buffer currently being read by the software
 * NR_BUF - Stores the number of the buffer currently being filled by the DMA core
 * BUFS - BUFS_?_HIGH - array storing the DMA addresses of the huge pages of buffers.
 * === OLD DESCRIPTION BELOW (to be reused...) ===
 * The code below implements a DAQ DMA engine, that writes the data to the
 * memory buffers, using the DMA.
 * It is assumed, that the memory buffers are based on hugepages
 * with size 2MB (maybe it should be parameterized?).
 * The 64-bit base addresses of the hugepages are stored in the block
 * memory in the FPGA. Here it is modeled as an "mem_bufs" array.
 * (should they really be 64-bit? the lowest 21 bits are always zero!
 * so we have only 43 bits. Is there any additional limit on the
 * upper bits?)
 *
 * Except of this, we need a control register, that holds configuration
 * information.
 * o) Number of memory buffers
 * o) Whether the acquisition is started or not
 * Additionally we need a runtime information
 * o) One huge pages stores a circular buffer for event descriptors - as 256 bit structures.
 *      => we need a special register for that!
 * o) Other huge pages are in a block memory - 2^N buffers
 * o) We receive the data until we get "tlast". After that we have to store the event.
 *    (how we can simulate that in QEMU?)
 *
 * So what must be in the "runtime information"?
 * o) Current write position - number of the HP page and offset in it.
 * o) Start position of the current event
 * o) Last unread position - number of the HP page and offset to it.
 *
 * Additionally we need a control ans status registers.
 * o) In control register we only start the engine.
 * o) In the status register we only stop it.
 *
 * ONE IMPORTANT REMARK:
 * The addresses of the huge pages are given as byte addresses.
 * All indexes and masks used to count word positions are as 64-bit word addresses

 * The QEMU model must contain also the emulated data source and its configuration.
 * Therefore there will be a few additional registers.
 *
 *
 * The code was written by Wojciech M. Zabolotny (wzab<at>ise.pw.edu.pl)
 * in March and April 2021, however it is significantly based on different
 * source codes provided in the QEMU sources.
 * Therefore I leave the original license:
 *
 * Copyright (c) 2003 Fabrice Bellard
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * The device is connected to the PCI bus - it's memory and interrupt resources are
 * reported to the host using the standard PC mechanisms.
 */

#define DEBUG_wzab1 1
// PCI IDs below are not officially registered! Use only for experiments!
//#define PCI_VENDOR_ID_WZAB 0xabba
//#define PCI_DEVICE_ID_WZAB_WZDAQ1 0x3342
// New IDs used by HLS version
#define PCI_VENDOR_ID_WZAB 0x32ab
#define PCI_DEVICE_ID_WZAB_WZDAQ1 0x8018
#include "qemu/osdep.h"
#include <inttypes.h>
#include "qemu/compiler.h"
#include <string.h>
#include "hw/sysbus.h"
#include "hw/hw.h"
#include "hw/pci/pci.h"
#include "hw/pci/msi.h"
#include "qemu/timer.h"
#include "hw/qdev-properties.h"
#include <string.h>
#include <endian.h>
#include <czmq.h>
#include "wzab_daq1.h"

static uint64_t pci_wzdaq1_read(void *opaque, hwaddr addr, unsigned size);
static void pci_wzdaq1_write(void *opaque, hwaddr addr, uint64_t val, unsigned size);
static uint64_t pci_wzdaq1_dummy_read(void *opaque, hwaddr addr, unsigned size);
static void pci_wzdaq1_dummy_write(void *opaque, hwaddr addr, uint64_t val, unsigned size);
static uint64_t pci_wzdaq1_agwb_read(void *opaque, hwaddr addr, unsigned size);
static void pci_wzdaq1_agwb_write(void *opaque, hwaddr addr, uint64_t val, unsigned size);

typedef struct WzDaq1State {
    PCIDevice pdev;
    MemoryRegion mmio0;
    MemoryRegion mmio;
    MemoryRegion mmio2;
    uint64_t write_ptr, read_ptr, ptr_mask;
    uint64_t hpage_size, hpage_mask;
    int hpage_shift;
    int nof_hp;
    uint64_t evt_write_ptr, evt_read_ptr, evt_ptr_mask;
    uint64_t evt_hp; //Address of HP keeping the event descriptors
    uint64_t evt_num; //Number of the event
    uint32_t error;
    uint64_t conf_dsn;
    uint32_t running;
    uint32_t irq_pending;
    uint32_t irq_enabled;
    //QEMUTimer * daq_timer;
    QemuThread thread;
    //State variables taken from the HLS implementation
    //function readin:
    //The variables in C are initialized differently, due to difference
    //between SW and HW implementation.
    
    //int count; //reset to 1 in HLS - not needed here, because we do not emulate bursts
    int nr_word; //reset to 1 in HLS - here to 0
    int bufleft; //reset to BUFLEN-1 - here to BUFLEN
    uint64_t after; //reset to 0
    //function prepare
    int soverrun; //in fact 1-bit, reset to 0
    uint32_t nr_buf; //reset to 0
    uint32_t nr_sgm; //reset to 0
    //State variables kept in GPIO
    uint32_t gpio_ctrl_outd; //initialized to 0
    uint32_t cur_buf; //initialized to 0
    uint32_t cur_segm; //initialized to 0
    //State variables kept in internal storage
    uint64_t descs; //initialized to 0
    uint64_t bufs[DAQ1_MAX_NOF_BUFS]; //Addresses of HPs creating the circular buffer
    int nof_bufs; //Number of buffers used.
    
} WzDaq1State;

#define TYPE_PCI_WZDAQ1 "pci-wzdaq1"

#define PCI_WZDAQ1(obj) OBJECT_CHECK(WzDaq1State, (obj), TYPE_PCI_WZDAQ1)

static Property wzab_daq1_properties[] = {
    DEFINE_PROP_UINT64("dsn", WzDaq1State, conf_dsn , INT64_MAX)
};

/*
 * Area used to control the DMA HLS core
 */

static const MemoryRegionOps pci_wzdaq1_mmio_ops = {
    .read = pci_wzdaq1_read,
    .write = pci_wzdaq1_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .impl = {
        .min_access_size = 4, //32-bit access!!
        .max_access_size = 4,
    },
    .valid = {
        .min_access_size = 4, //32-bit access!!
        .max_access_size = 4,
    },   
};

/*
* Fake area - imitating the Xilinx PCIe bridge
*/
static const MemoryRegionOps pci_wzdaq1_mmio0_ops = {
    .read = pci_wzdaq1_dummy_read,
    .write = pci_wzdaq1_dummy_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
  .impl = {
        .min_access_size = 4, //32-bit access!!
        .max_access_size = 4,
    },
    .valid = {
        .min_access_size = 4, //32-bit access!!
        .max_access_size = 4,
    },
};

static uint64_t pci_wzdaq1_dummy_read(void *opaque, hwaddr addr, unsigned size)
{
#ifdef DEBUG_wzab1
    printf("XLX Memory read: address %" PRIx64 "\n", (uint64_t) addr);
#endif
   return 0x0bada4ea;
}

void pci_wzdaq1_dummy_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
#ifdef DEBUG_wzab1
    printf("XLX Memory written: addres = %" PRIx64 ", val=%" PRIx64 "\n", (uint64_t) addr, (uint64_t) val);
#endif
   return;
}

/*
* Area imitating the AGWB-managed addresses
*/

static const MemoryRegionOps pci_wzdaq1_mmio2_ops = {
    .read = pci_wzdaq1_agwb_read,
    .write = pci_wzdaq1_agwb_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
  .impl = {
        .min_access_size = 4, //32-bit access!!
        .max_access_size = 4,
    },
    .valid = {
        .min_access_size = 4, //32-bit access!!
        .max_access_size = 4,
    },
};

static uint64_t pci_wzdaq1_agwb_read(void *opaque, hwaddr addr, unsigned size)
{
#ifdef DEBUG_wzab1
    printf("AGWB read: address %" PRIx64 "\n", (uint64_t) addr);
#endif
   return 0x0a93b900d;
}

void pci_wzdaq1_agwb_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
#ifdef DEBUG_wzab1
    printf("AGWB written: addres = %" PRIx64 ", val=%" PRIx64 "\n", (uint64_t) addr, (uint64_t) val);
#endif
   return;
}
/*
  static bool wzdaq1_msi_enabled(WzDaq1State * s)
  {
  return msi_enabled(&s->pdev);
  }
*/


static void wzdaq1_soft_reset(WzDaq1State *s)
{
#ifdef DEBUG_wzab1
    printf("wzdaq1 soft reset!\n");
#endif
    //Copied from the HLS implementation
    s->nr_word = 0;
    s->bufleft = DAQ1_BUFLEN_IN_WORDS;
    s->soverrun = 0;
    s->nr_buf = 0;
    s->nr_sgm = 0;
    s->irq_enabled = 0;
    s->after = 0;
}

static void wzdaq1_reset (void * opaque)
{
    WzDaq1State *s = opaque;
    //memset(&s,0,sizeof(s));
    wzdaq1_soft_reset(s);
#ifdef DEBUG_wzab1
    printf("wzdaq1 reset!\n");
#endif
}

static inline void check_irq(WzDaq1State *s)
{
    if(! s->irq_enabled) {
        pci_irq_deassert(&s->pdev);
    } else {
        if((s->soverrun) ||
           (s->cur_segm != s->nr_sgm)) {
            pci_irq_assert(&s->pdev);
        } else {
        pci_irq_deassert(&s->pdev);
        }            
    }
}

/* called for read accesses to our register memory area */
static uint64_t pci_wzdaq1_read(void *opaque, hwaddr addr, unsigned size)
{
#ifdef DEBUG_wzab1
    printf("Memory read: address %" PRIx64 "\n", (uint64_t) addr);
#endif
    WzDaq1State *s = opaque;
    uint64_t ret=0xbada4ea55aa55aa; //Special value returned when accessed non-existing register
    //addr = addr/8;
    //Special cases
    if(addr==DAQ1_DESCS) {
        ret = s->descs & 0xffffffff;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==DAQ1_DESCS + 4) {
        ret = (s->descs >> 32) & 0xffffffff;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==DAQ1_CUR_SEGM) {
        ret = s->cur_segm;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==DAQ1_NR_SEGM) {
        ret = s->nr_sgm;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==DAQ1_CUR_BUF) {
        ret = s->cur_buf;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==DAQ1_NR_BUF) {
        ret = s->nr_buf;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==DAQ1_NOF_BUFS) {
        ret = s->nof_bufs;
#ifdef DEBUG_wzab1
        printf(" value %"PRIx64"\n",ret);
#endif
        return ret;
    }
    if(addr==AXI_CTRL_OUTD) {
        ret = s->gpio_ctrl_outd;
        return ret;
    }
    if(addr==AXI_CTRL_IND) {
        ret = 0;
        if(s->soverrun) 
          ret |= (1 << CTRL_IND_BIT_OVERRUN);
        if(s->cur_segm != s-> nr_sgm)
          ret |= (1 << CTRL_IND_BIT_SGMAV);        
        return ret;
    }
    if (( addr >= DAQ1_BUFS ) && ( addr <= DAQ1_BUFS_HIGH )) {
        ret = s->bufs[(addr-DAQ1_BUFS)/8];
        // Read the hugepage address from the buffer
        if(addr & 4) {
           //Upper 4 bytes
           ret >>= 32;
        }
        ret &= 0xffffffff;
        return ret;
    }
    return ret;
}


/* called for write accesses to our register memory area */
void pci_wzdaq1_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{
    WzDaq1State *s = opaque;
#ifdef DEBUG_wzab1
    printf("Memory write: address = %" PRIx64 ", val = %" PRIx64 "\n", (uint64_t) addr, (uint64_t) val);
#endif
    /* convert to wzdaq1 memory offset */
    //addr = (addr/8);
    switch(addr) {
    case DAQ1_DESCS:
        s->descs = (s->descs & 0xffffffff00000000LL) | (val & 0xffffffff);
        break;
    case DAQ1_DESCS+4:
        s->descs = (s->descs & 0xffffffff) | ((val & 0xffffffff) << 32);
        break;
    case DAQ1_CUR_SEGM:
        s->cur_segm = val;
        check_irq(s);
        break;
    case DAQ1_NR_SEGM:
        //That's read-only register
        //s->nr_segm = val;
        break;
    case DAQ1_CUR_BUF:
        s->cur_buf = val;
        break;
    case DAQ1_NR_BUF:
        //That's read-only register
        //s->nr_buf = val;
        break;
    case DAQ1_NOF_BUFS:
        s->nof_bufs = val;
        break;
        // Access to the CTRL GPIO!
        //AXI_GPIO_ID_IND
        //AXI_GPIO_CTRL_IND
        //AXI_GPIO_CTRL_OUTD
    case AXI_CTRL_OUTD:
        s->gpio_ctrl_outd = val;
        // Here we will handle actions associated with particular control bits
        // Please note, that we should also handle changes...
        if(val & (1 << 0)) {
            // AP_START
            s->running = 1;
        } else {
            s->running = 0;
        }
        if(val & (1 << 1)) {
            // AP_nRST
        } else {
            //Reset the internal variables (as in the HLS code)
            wzdaq1_soft_reset(s);
        }
        if(val & (1 << 2)) {
            // AP_SRC_START
        }
        if(val & (1 << 3)) {
            // AP_IRQ_enable
            s->irq_enabled = 1;
        } else { 
            s->irq_enabled = 0;
        }
        check_irq(s);
    }
    if (( addr >= DAQ1_BUFS ) && ( addr <= DAQ1_BUFS_HIGH )) {
        // Write the hugepage address to the buffer
        uint64_t tmp = s->bufs[(addr-DAQ1_BUFS)/8];
	if(addr & 4) {
	   // Upper 32 bits
	   s->bufs[(addr-DAQ1_BUFS)/8] = (tmp & 0xffffffff) | ((val & 0xffffffff) << 32);
	} else {
	   // Lower 32 bits
	   s->bufs[(addr-DAQ1_BUFS)/8] = (tmp & 0xffffffff00000000LL) | (val & 0xffffffff);
	}
    }
}

/* The procedure changes the data segment.
 * Currently we write only the address of the last word
 * in the circular buffer.
 *
 * However, it creates one problem. I don't want the kernel
 * to access the descriptors area (I don't have kernel mapping for it).
 * How can I check in the kernel if the event is ready then?
 * If I advance the write pointer when completing the previous event,
 * I'll get an error, if the next event is not processed yet.
 * However, that's OK as long, as I don't try to write a new event.
 *
 * I could encode the state of the event in the least significant bit of the
 * write pointer. 0 - the event is being written, 1 - the event is completed.
 *
 * So now I simply call start_segment immediately after end_segment...
 */

static int change_segment(WzDaq1State * s)
{
    if(s->soverrun) return -1;
    int new_nr_sgm = s->nr_sgm + 1;
    if(new_nr_sgm == DAQ1_NUM_EVT_DESCS)
        new_nr_sgm = 0;
    if(new_nr_sgm == s->cur_segm) {
        s->soverrun = 1;        
        return -2;
    } else {
        //Write the position of the first word in the next segment
        //to the descriptor
        uint8_t desc[32];
        memset(desc,0,32);
        uint64_t after = s->nr_buf * DAQ1_BUFLEN_IN_WORDS + s->nr_word;
        * (uint64_t *) (desc + 8) = htole64(after);
        * (uint64_t *) (desc + 0) = htole64(s->after);
        pci_dma_write(&s->pdev,s->descs + 32*s->nr_sgm,&desc,sizeof(desc));
        s->nr_sgm = new_nr_sgm;
        s->after = after;
    }
    return 0;
}

/* The procedure that adds words to the cyclic buffer */
static int add_words(WzDaq1State * s, void * wbuf, int nwords)
{
    // Check for overrun
    if(s->soverrun) return -1;
    // We write to the current buffer, until there is space
    while(nwords > 0) {
        int to_write = nwords; //number of words to be written
        if (to_write > s->bufleft) to_write = s->bufleft;
        pci_dma_write(&s->pdev,s->bufs[s->nr_buf]+32*s->nr_word,wbuf,to_write*32);
        s->nr_word += to_write;
        s->bufleft -= to_write;
        if(s->bufleft == 0) {
            //switch to the new buffer, if possible
            int new_nr_buf = (s->nr_buf + 1);
            if((new_nr_buf == s->nof_bufs) || (new_nr_buf == DAQ1_MAX_NOF_BUFS))
                new_nr_buf = 0;
            if(new_nr_buf == s->cur_buf) {
                // No free buffer
                s->soverrun = 1;
                return -2;
            } else {
                s->nr_buf = new_nr_buf;
                s->bufleft = DAQ1_BUFLEN_IN_WORDS;
                s->nr_word = 0;
            }
        }
        wbuf += to_write*32;
        nwords -= to_write;
    }
    return 0;
}

/* That procedure receives the events in a separate thread and writes data to the cyclic buffer */
static void * receive_data_thread(void * arg)
{
    WzDaq1State * s = (WzDaq1State *) arg;
    zsock_t *pull = zsock_new_pair ("");
    zsock_bind(pull,"tcp://0.0.0.0:*[3000-]");
#ifdef DEBUG_wzab1
    printf("Receive thread started\n");
#endif
    while(1) {
        zmsg_t * msg = zmsg_recv (pull);
        //The engine must be running
        printf("Received frame\n");
        if(s->running) {
            //This must be a single frame message!
            if(zmsg_size(msg) != 1) {
                //Handle improper size of the message
            } else {
                zframe_t * frame = zmsg_first(msg);
                //Process the frame
                void * ptr = (void *)zframe_data(frame);
                if(zframe_size(frame) % 32) {
                    printf("Frame size not N*32\n");
                } else {
                    //Check the type of the record
                    int is_t,is_d, is_q;
                    is_t = (memcmp(ptr,"WZDAQ1-T",8) == 0);
                    is_d = (memcmp(ptr,"WZDAQ1-D",8) == 0);
                    is_q = (memcmp(ptr,"WZDAQ1-Q",8) == 0);
                    if ( is_t || is_d ) {
                        //Calculate the number of words
                        int nwords = zframe_size(frame)/32 - 1;
                        if (nwords <= 0) {
                            printf("Error: WZDAQ1-? empty data frame?\n");
                            abort();
                        }
                        printf("Frame: %d words\n",nwords);
                        //Add the words to the circular buffer and update
                        //s->nr_word
                        add_words(s,ptr+32,nwords);                            
                        //If TLAST was set, change the segment
                        if (is_t) {
                            change_segment(s);
                        }
                        //Update the IRQ status
                        check_irq(s);
                    } else if (is_q) {
                        printf("End of run!\n");
                        break;
                    } else {
                        printf("Error: No data type!");
                        abort();
                    }
                }
            }
        }
        zmsg_destroy(&msg);
    }
    zsock_destroy (&pull);
    return 0;
}

static void pci_wzdaq1_realize (PCIDevice *pdev, Error **errp)
{
    WzDaq1State *s = PCI_WZDAQ1(pdev);
    uint8_t *c = s->pdev.config;

    /* TODO: RST# value should be 0. */
    c[PCI_INTERRUPT_PIN] = 1;
    memory_region_init_io(&s->mmio0,OBJECT(s),&pci_wzdaq1_mmio0_ops,s,
                          "pci-wzdaq1-mmio0", 0x10000000);
    pci_register_bar (&s->pdev, 0,  PCI_BASE_ADDRESS_SPACE_MEMORY | PCI_BASE_ADDRESS_MEM_TYPE_64, &s->mmio0);
    memory_region_init_io(&s->mmio,OBJECT(s),&pci_wzdaq1_mmio_ops,s,
                          "pci-wzdaq1-mmio", 0x40000);
    pci_register_bar (&s->pdev, 2,  PCI_BASE_ADDRESS_SPACE_MEMORY | PCI_BASE_ADDRESS_MEM_TYPE_64, &s->mmio);
    memory_region_init_io(&s->mmio2,OBJECT(s),&pci_wzdaq1_mmio2_ops,s,
                          "pci-wzdaq1-agwb", 0x8000000);
    pci_register_bar (&s->pdev, 4,  PCI_BASE_ADDRESS_SPACE_MEMORY | PCI_BASE_ADDRESS_MEM_TYPE_64, &s->mmio2);
    //Timer is not used, data are delivered by ZMQ!
    //s->daq_timer = timer_new_ns(QEMU_CLOCK_VIRTUAL, wzdaq1_tick, s);
    //Add the thread receiving the data
    qemu_thread_create(&s->thread, "receive_data", receive_data_thread, s,
                       QEMU_THREAD_JOINABLE);
    //AUD_register_card ("wz_adc1", &s->card);
    if (pcie_endpoint_cap_v1_init(pdev, 0x0e0) < 0) {
        hw_error("Failed to initialize PCIe capability");
    }
    pcie_dev_ser_num_init(pdev, (uint16_t) 0x100,(uint64_t) s->conf_dsn);
    wzdaq1_reset (s);
    //return 0;
}



static void pci_wzdaq1_init(Object *obj)
{
}

static void
pci_wzdaq1_uninit(PCIDevice *dev)
{
    WzDaq1State *s = PCI_WZDAQ1(dev);
    wzdaq1_reset(s);

    qemu_thread_join(&s->thread);
    //timer_free(s->daq_timer);
}

static void qdev_pci_wzdaq1_reset(DeviceState *dev)
{
    WzDaq1State *s = PCI_WZDAQ1(dev);
    wzdaq1_reset(s);
}

static void pci_wzdaq1_class_init(ObjectClass *class, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(class);
    PCIDeviceClass *k = PCI_DEVICE_CLASS(class);

    device_class_set_props(dc, wzab_daq1_properties);
    k->realize = pci_wzdaq1_realize;
    k->exit = pci_wzdaq1_uninit;
    k->vendor_id = PCI_VENDOR_ID_WZAB;
    k->device_id = PCI_DEVICE_ID_WZAB_WZDAQ1;
    k->revision = 0x00;
    k->class_id = PCI_CLASS_OTHERS;
    dc->desc = "PCI demo BM DMA ADC";
    set_bit(DEVICE_CATEGORY_MISC, dc->categories);
    dc->reset = qdev_pci_wzdaq1_reset;
}


static void pci_wzdaq1_register_types(void)
{
    static InterfaceInfo interfaces[] = {
        { INTERFACE_PCIE_DEVICE },
        { },
    };
    static const TypeInfo pci_wzdaq1_info = {
        .name          = TYPE_PCI_WZDAQ1,
        .parent        = TYPE_PCI_DEVICE,
        .instance_size = sizeof(WzDaq1State),
        .instance_init = pci_wzdaq1_init,
        .class_init    = pci_wzdaq1_class_init,
        .interfaces = interfaces,
    };

    type_register_static(&pci_wzdaq1_info);
}

type_init(pci_wzdaq1_register_types)


